# Generated by Django 5.0.1 on 2024-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_customuser_userregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
